server:
  port: 8181
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      location: E:\Project\microblog\microblog_backend
  elasticsearch:
    rest:
      uris: localhost:9200
  datasource:
    url: jdbc:mysql://localhost:3306/microblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  main:
    allow-bean-definition-overriding: true
  aop:
    proxy-target-class: true
    auto: true
logging:
  config: classpath:logback-spring.xml