server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
#  redis:
#    host: localhost
#    port: 6379
#    timeout: 5000
#  kafka:
#    topicsUser:32882
#    bootstrap-servers: localhost:9092
#    producer:
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer